version: "3.1"

services:
  mongodb:
    env_file: ../.env
    image: mongo:latest
    container_name: ${MONGO_CONTAINER_NAME}
    restart: always
    network_mode: "host"
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}

volumes:
  mongodb:
