version: "3.8"
services:
  authdb:
    restart: always
    image: postgres:latest
    volumes:
      - authdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - ../.env
    ports:
      - "5432:5432"


volumes:
  authdb:
