services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    env_file:
      - .env
    networks:
      - gennet_ai_network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  authdb:
    restart: always
    image: postgres:latest
    container_name: authdb
    volumes:
      - authdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    networks:
      - gennet_ai_network

  api-v2:
    restart: always
    container_name: api-v2
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - authdb
      - mongodb
    volumes:
      - h2ogpt_data:${H2OGPT_RES_DIR}
      - static:${STATIC_FILES}
      - ./:/app
    env_file:
      - .env
    networks:
      - gennet_ai_network
    ports:
      - "8000:8000"
    entrypoint: ["/bin/sh", "-c"]
    command:
      [
        "python /app/auth/src/backend_pre_start.py; cd /app/auth && alembic upgrade head; cd /app && uvicorn main:app --host 0.0.0.0 --reload"
      ]



networks:
  gennet_ai_network:
    driver: bridge

volumes:
  static:
  authdb:
  mongodb_data:
  h2ogpt_data:
